# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nomain

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello From DasLearning.in"
  displayName: 'Run a one-line script'
